### ISSUE TITLE
OpenHealthContext fixes

### ISSUE THREAD

**Issue by chicco785** [smartsdk/dataModels#2]
Currently the schema cannot be validated since it references json files that are not valid json schemas. But only pointer to the OpenHealthContext documentation. I recommend to reference directly the correct json schemas in the OpenHealthContext base.

`"body_weight": {  
	      "$ref": "http://www.openmhealth.org/schema/omh/body-weight-1.0.json"
	   },`

Also check the documentation. 

`"omh:body_weight": {  
      "value": "89",
      "type": "kg"
   },`

Shouldn't `type` be `unit` ?

**Comment by netzahdzc** [comment]
Hi there, thanks for taking a look. I just made an update in which your observation (about son references) has been attended.

**Comment by netzahdzc** [comment]
About using type instead of unit: to be honest I wasn't sure about it since we are combining two models. I will updated based on your comments; thought.
