### ISSUE TITLE
User in OpenHealthContext

### ISSUE THREAD

**Issue by chicco785** [smartsdk/dataModels#3]
I tend to think that this data, that are partially sensible and beyond that quite static, should not be modelled in NGSI, but rather stored in the FIWARE IDM, or in a specific data base of the application.

**Comment by netzahdzc** [comment]
Hi there, I'm not sure if you are referring to the whole health data-model in general or to a specific schema. Nevertheless, in a previous update I was suggested to remove personal data such as username, and emails. Thus, we will be keeping just identification. 

In general, I presume the data we are modelling is not susceptive to be used as signature; as gps data could be. Anyways, in the near future we might be taking into account an ethical bureau supervision.
